name: WildFly ha-singleton-deployment Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'ha-singleton-deployment/**'
      - '.github/workflows/quickstart_ci.yml'

jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: ha-singleton-deployment
      TEST_OPENSHIFT: false
